export const USER_SIGNIN_REQUEST= "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCESS= "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILURE= "USER_SIGNIN_FAILURE";
export const USER_SIGNUP_REQUEST= "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCESS= "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE= "USER_SIGNUP_FAILURE";